//
// Created by 28318 on 2023/9/1.
//

#ifndef C_INSERTANDSELECT_C_ENUMS_H
#define C_INSERTANDSELECT_C_ENUMS_H

enum MetaCommandResult {
    META_COMMAND_SUCCESS,
    META_COMMAND_UNRECOGNIZED_COMMAND,
    META_COMMAND_HELP
};
enum PrepareResult {
    PREPARE_SUCCESS,
    PREPARE_UNRECOGNIZED_STATEMENT,
    PREPARE_SYNTAX_ERROR
};

enum StatementType {
    STATEMENT_INSERT,
    STATEMENT_SELECT
};

enum ExecuteResult{
    EXECUTE_SUCCESS,
    EXECUTE_TABLE_FULL
};

#endif //C_INSERTANDSELECT_C_ENUMS_H
